In [50]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Seattle_Pet_Licenses.csv')

In [3]:
df.head()

,License Issue Date,License Number,Animal's Name,Species,Primary Breed,Secondary Breed,ZIP Code
0,April 19 2003,200097.0,Tinkerdelle,Cat,Domestic Shorthair,NaN,98116
1,February 07 2006,75432.0,Pepper,Cat,Manx,Mix,98103
2,August 31 2012,578859.0,Grey Fox,Cat,Siamese,Mix,98125
3,November 14 2013,832989.0,Hannah,Cat,Domestic Longhair,NaN,98133
4,April 03 2014,433713.0,Daisy,Cat,Domestic Shorthair,NaN,98117

In [4]:
df['License Issue Date'] = pd.to_datetime(df["License Issue Date"])

In [7]:
# Yay, we have 2018 data in there.
df.sort_values(by=['License Issue Date'], ascending=False)

,License Issue Date,License Number,Animal's Name,Species,Primary Breed,Secondary Breed,ZIP Code
55960,2018-03-10,902201.0,Nala,Dog,Kai Ken,NaN,98103
19031,2018-03-10,140093.0,Mitchell,Cat,Domestic Shorthair,Mix,98121
38020,2018-03-10,140091.0,Eddie,Dog,Beagle,NaN,98108
38019,2018-03-10,128110.0,Bugs,Dog,"Spaniel, American Cocker",NaN,98125
38018,2018-03-10,110035.0,Grendel,Dog,Chow Chow,"Retriever, Labrador",NaN
19030,2018-03-10,128111.0,Phoebe,Cat,Siamese,Desert Lynx,98125
19029,2018-03-10,104298.0,Scully,Cat,Domestic Shorthair,Mix,98144
19028,2018-03-10,104297.0,Mulder,Cat,Domestic Shorthair,Mix,98144
38021,2018-03-10,140092.0,Osbert,Dog,Maltese,Mix,98122
55959,2018-03-10,15970.0,Ziggie,Dog,Miniature Pinscher,NaN,98106
55958,2018-03-10,102232.0,Caledonia,Dog,Bernese Mountain Dog,NaN,98116
55957,2018-03-10,112062.0,Cricket,Dog,"Poodle, Miniature","Spaniel, American Cocker",98126
55956,2018-03-10,84139.0,Carly Rose,Dog,"Retriever, Labrador",NaN,98117
55952,2018-03-09,NaN,Ruby Rose,Dog,"Terrier, English Staffordshire",NaN,98126
38010,2018-03-09,140918.0,Din Din,Dog,Australian Shepherd,NaN,98119
19024,2018-03-09,74348.0,Pickles,Cat,Domestic Shorthair,NaN,98103
19025,2018-03-09,964212.0,Ghost,Cat,Domestic Shorthair,NaN,98125
19026,2018-03-09,964218.0,Patinkin,Cat,Domestic Shorthair,NaN,98125
19027,2018-03-09,107907.0,Fizz,Cat,Domestic Longhair,NaN,98133
55954,2018-03-09,NaN,Zoe,Dog,German Shepherd,NaN,98105
55955,2018-03-09,NaN,Chloe,Dog,Havanese,NaN,98133
38012,2018-03-09,140697.0,Pad Thai,Dog,Alaskan Klee Kai,NaN,98102
38011,2018-03-09,140917.0,Diego,Dog,Maltese,"Poodle, Miniature",98119
55951,2018-03-09,100477.0,Wombat,Dog,"Terrier, Staffordshire Bull",NaN,98126
38013,2018-03-09,140916.0,Marley,Dog,"Terrier, Soft Coated Wheaten","Poodle, Standard",NaN
38014,2018-03-09,NaN,Nordic IV,Dog,"Retriever, Golden","Retriever, Labrador",98122
38015,2018-03-09,NaN,Leo,Dog,"Retriever, Labrador",Great Dane,98107
38016,2018-03-09,NaN,Kooper,Dog,Mix,NaN,98106
38017,2018-03-09,84006.0,Cole,Dog,Coonhound,Mix,98117
19023,2018-03-09,74342.0,Cowboy,Cat,Domestic Shorthair,NaN,98103
...,...,...,...,...,...,...,...
38033,2014-04-07,81166.0,Olive,Dog,"Terrier, Bull",NaN,98125
38034,2014-04-07,138661.0,Annie,Dog,Bichon Frise,"Poodle, Miniature",98125
38035,2014-04-07,138618.0,Brie,Dog,Bichon Frise,NaN,98125
19042,2014-04-07,834754.0,Gizmo,Dog,Havanese,NaN,98108
38032,2014-04-04,215429.0,Precious,Dog,"Terrier, Jack Russell",NaN,98116
38031,2014-04-03,280523.0,Abby,Dog,"Retriever, Labrador",NaN,98119
19041,2014-04-03,214189.0,Link,Dog,"Retriever, Labrador",NaN,98125
4,2014-04-03,433713.0,Daisy,Cat,Domestic Shorthair,NaN,98117
38030,2014-04-03,139259.0,Po'ele,Dog,"Retriever, Labrador",NaN,98115
19040,2014-04-02,331286.0,Buddy,Dog,"Schnauzer, Miniature",NaN,98144
19039,2014-03-31,278788.0,Phinnegan,Dog,Australian Shepherd,NaN,98103
38029,2014-03-19,141023.0,Lucy,Dog,"Poodle, Miniature","Spaniel, American Cocker",98199
19038,2014-01-28,83614.0,Pepsi,Dog,Australian Shepherd,Bearded Collie,98115
38028,2014-01-21,212932.0,Rosie,Dog,"Retriever, Labrador",German Shepherd,98199
19037,2014-01-17,903830.0,Mitchell,Dog,"Spaniel, English Springer",NaN,98144
3,2013-11-14,832989.0,Hannah,Cat,Domestic Longhair,NaN,98133
38027,2012-12-01,893696.0,Fancy,Dog,Maltese,NaN,98122
19036,2012-11-25,899061.0,Jake,Dog,"Retriever, Labrador",NaN,NaN
38025,2012-10-15,820181.0,Midnight,Dog,"Chihuahua, Short Coat",NaN,98118
38026,2012-10-15,820182.0,Blackie,Dog,"Retriever, Labrador",Mix,98118
2,2012-08-31,578859.0,Grey Fox,Cat,Siamese,Mix,98125
19035,2012-08-30,584062.0,Cooper,Dog,"Chihuahua, Short Coat",NaN,98105
38024,2011-03-29,141222.0,Jenkey,Dog,Australian Cattle Dog,Mix,98106
19034,2008-12-01,957147.0,Finigan,Dog,"Spaniel, Irish Water",NaN,98107
38023,2008-11-12,900555.0,Emily,Dog,"Terrier, Boston",NaN,98107
19033,2008-03-31,135493.0,Oscar,Dog,"Dachshund, Miniature Smooth Haired",NaN,98104
19032,2008-03-20,135598.0,Buddy,Dog,"Retriever, Labrador",Mix,98133
1,2006-02-07,75432.0,Pepper,Cat,Manx,Mix,98103
38022,2004-02-04,109299.0,Chivja,Dog,Saint Bernard,NaN,98101
0,2003-04-19,200097.0,Tinkerdelle,Cat,Domestic Shorthair,NaN,98116

In [56]:
# I think there needs to be some more data cleaning happening...
# Are there blank or short cat names?
df["Animal\'s Name"].isnull().sum()

816

In [ ]:
# !!! THERE ARE 816 ANIMALS WITHOUT NAMES!!!

In [66]:
df[pd.isnull(df["Animal\'s Name"])]

,License Issue Date,License Number,Animal's Name,Species,Primary Breed,Secondary Breed,ZIP Code
54,2015-08-06,578687.0,NaN,Cat,Domestic Shorthair,NaN,98144
83,2015-11-16,269837.0,NaN,Cat,Domestic Shorthair,NaN,98112
147,2015-11-30,21795.0,NaN,Cat,Domestic Medium Hair,NaN,98103
167,2015-12-02,140679.0,NaN,Cat,Domestic Shorthair,NaN,98103
214,2015-12-15,897476.0,NaN,Cat,Domestic Shorthair,NaN,98136
240,2015-12-18,896415.0,NaN,Cat,Domestic Medium Hair,NaN,98136
293,2016-01-08,822915.0,NaN,Cat,Domestic Shorthair,Russian Blue,98199
300,2016-01-13,730389.0,NaN,Cat,Domestic Shorthair,NaN,98121
310,2016-01-25,896246.0,NaN,Cat,Domestic Shorthair,NaN,98125
333,2016-02-16,349529.0,NaN,Cat,Domestic Shorthair,NaN,98103
355,2016-03-03,110791.0,NaN,Cat,Siamese,Mix,98115
356,2016-03-03,110795.0,NaN,Cat,Domestic Shorthair,Mix,98133
357,2016-03-03,110796.0,NaN,Cat,Domestic Shorthair,Mix,98107
363,2016-03-03,110797.0,NaN,Cat,Domestic Shorthair,Mix,98133
365,2016-03-03,110799.0,NaN,Cat,Domestic Medium Hair,Mix,98115
366,2016-03-03,110835.0,NaN,Cat,Domestic Shorthair,Mix,98117
367,2016-03-03,110836.0,NaN,Cat,Domestic Medium Hair,Mix,98122
368,2016-03-03,110837.0,NaN,Cat,Domestic Shorthair,Mix,98109
460,2016-03-08,133139.0,NaN,Cat,Domestic Medium Hair,NaN,98126
482,2016-03-09,140780.0,NaN,Cat,Domestic Medium Hair,NaN,98125
541,2016-03-12,110833.0,NaN,Cat,Domestic Shorthair,Mix,98122
622,2016-03-16,133468.0,NaN,Cat,Domestic Shorthair,NaN,98107
662,2016-03-19,128199.0,NaN,Cat,Domestic Medium Hair,NaN,98107
692,2016-03-22,128153.0,NaN,Cat,Domestic Shorthair,NaN,98136
763,2016-03-28,129774.0,NaN,Cat,Domestic Shorthair,NaN,98112
925,2016-04-07,113658.0,NaN,Cat,Domestic Shorthair,Mix,98115
926,2016-04-07,113661.0,NaN,Cat,Domestic Shorthair,Mix,98109
927,2016-04-07,113663.0,NaN,Cat,Domestic Longhair,Mix,98125
931,2016-04-07,113664.0,NaN,Cat,Siamese,Domestic Shorthair,98133
932,2016-04-07,113665.0,NaN,Cat,Domestic Shorthair,Mix,98103
...,...,...,...,...,...,...,...
45667,2017-01-26,127314.0,NaN,Dog,"Chihuahua, Short Coat",NaN,98144
45672,2017-01-26,24041.0,NaN,Dog,Australian Shepherd,Dalmatian,98115
46348,2017-03-08,131355.0,NaN,Dog,Australian Shepherd,Mix,98115
46902,2017-04-04,119878.0,NaN,Dog,Pomeranian,"Chihuahua, Short Coat",98103
47153,2017-04-13,119858.0,NaN,Dog,"Chihuahua, Short Coat",Mix,98106
47184,2017-04-14,84098.0,NaN,Dog,"Retriever, Labrador",NaN,98125
47486,2017-04-26,194099.0,NaN,Dog,Border Collie,Mix,98136
47974,2017-05-16,263830.0,NaN,Dog,"Dachshund, Standard Smooth Haired",NaN,98146
48071,2017-05-18,361209.0,NaN,Dog,"Terrier, Yorkshire",NaN,98146
48687,2017-06-10,356981.0,NaN,Dog,Terrier,Mix,98116
48756,2017-06-13,355686.0,NaN,Dog,"Retriever, Labrador",Mix,98117
48788,2017-06-13,142002.0,NaN,Dog,Shiba Inu,NaN,98125
49927,2017-07-26,280364.0,NaN,Dog,"Terrier, American Staffordshire",NaN,98107
49985,2017-07-28,126064.0,NaN,Dog,"Retriever, Labrador",Mix,98112
50597,2017-08-15,582692.0,NaN,Dog,"Retriever, Labrador",Mix,98105
50881,2017-08-25,133933.0,NaN,Dog,Pekingese,Mix,98118
51010,2017-08-30,581054.0,NaN,Dog,"Terrier, Staffordshire Bull","Terrier, Boston",98117
51754,2017-09-29,439249.0,NaN,Dog,Pomeranian,NaN,98144
51881,2017-10-05,135566.0,NaN,Dog,Xoloitzcuintli,NaN,98107
52243,2017-10-18,830161.0,NaN,Dog,Terrier,Shepherd,98108
52332,2017-10-24,833016.0,NaN,Dog,Pekingese,NaN,98103
52361,2017-10-24,834187.0,NaN,Dog,Pug,Beagle,98119
52375,2017-10-24,826184.0,NaN,Dog,"Retriever, Labrador",NaN,98136
52428,2017-10-25,137128.0,NaN,Dog,"Retriever, Golden","Poodle, Standard",98199
52440,2017-10-26,833003.0,NaN,Dog,"Spaniel, English Springer",NaN,98144
52513,2017-10-30,582170.0,NaN,Dog,Terrier,Mix,98125
52515,2017-10-30,723191.0,NaN,Dog,Papillon,NaN,98125
53845,2017-12-16,955378.0,NaN,Dog,"Dachshund, Standard Smooth Haired",NaN,98125
53961,2017-12-19,104923.0,NaN,Dog,Terrier,Mix,98144
54165,2017-12-29,136219.0,NaN,Dog,"Retriever, Labrador",NaN,98118

In [67]:
df = df[~pd.isnull(df["Animal\'s Name"])]

In [8]:
# Let's create separate names for dogs and cats.

In [68]:
dog_names = df[df.Species=='Dog']["Animal's Name"]

In [69]:
dog_names.to_csv('dog_names.csv', index=False)

In [70]:
cat_names = df[df.Species=='Cat']["Animal's Name"]

In [71]:
cat_names.to_csv('cat_names.csv', index=False)

In [72]:
!head dog_names.csv

Winston
Charlie
Louie
Finn
Cole
Moka
Bill
Moose
Hero
Boss

In [73]:
!head cat_names.csv

Tinkerdelle
Pepper
Grey Fox
Hannah
Daisy
Kukula
Stanleigh
Gunner
Rhiannon
Leto

In [19]:
# DOGS

In [74]:
# get a single long string of strain names separated by newline chars
with open('dog_names.csv') as f:
    file = f.read()

In [ ]:
len(file)

In [76]:
# Following pytorch example I used previously

In [77]:
import random
import string
import re

all_characters = string.printable
n_characters = len(all_characters)

In [78]:
chunk_len = 100
file_len = len(file)
def random_chunk():
    '''filelen is length of chars in file'''
    start_index = random.randint(0, file_len - chunk_len)
    end_index = start_index + chunk_len + 1
    return file[start_index:end_index]

In [79]:
random_chunk()

'o\nToby\nLuke\nJimmy Dean\nSedona\nWebster\nBode\nHampton\nMax\nTeddy\nDuke\nOtto\nMilo\nNova\nMax\nMax\nNazzy\nWalden'

In [80]:
# Build the Model
import torch
import torch.nn as nn
from torch.autograd import Variable

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, n_layers=1):
        super(RNN, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.n_layers = n_layers
        
        self.encoder = nn.Embedding(input_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size, n_layers)
        self.decoder = nn.Linear(hidden_size, output_size)
        
    def forward(self, input, hidden):
        input = self.encoder(input.view(1,-1))
        output, hidden = self.gru(input.view(1,1,-1) ,hidden)
        output = self.decoder(output.view(1, -1))
        return output, hidden
    
    def init_hidden(self):
        return Variable(torch.zeros(self.n_layers, 1, self.hidden_size))

In [81]:
def char_tensor(string_):
    tensor = torch.zeros(len(string_)).long()
    for c in range(len(string_)):
        tensor[c] = all_characters.index(string_[c])
    return Variable(tensor)

print(char_tensor('abcDEF'))

Variable containing:
 10
 11
 12
 39
 40
 41
[torch.LongTensor of size 6]

In [82]:
def random_training_set():
    chunk = random_chunk()
    inp = char_tensor(chunk[:-1])
    target = char_tensor(chunk[1:])
    return inp, target

In [83]:
# Evaluating
def evaluate(prime_str='A', predict_len=100, temperature=0.8):
    hidden = decoder.init_hidden()
    prime_input = char_tensor(prime_str)
    predicted = prime_str
    
    for p in range(len(prime_str)-1):
        _,hidden = decoder(prime_input[p], hidden)
    inp = prime_input[-1]
    
    for p in range(predict_len):
        output, hidden = decoder(inp, hidden)
        
        output_dist = output.data.view(-1).div(temperature).exp()
        top_i = torch.multinomial(output_dist, 1)[0]
        
        predicted_char = all_characters[top_i]
        predicted += predicted_char
        inp = char_tensor(predicted_char)
        
    return predicted

In [84]:
# Training
import time, math

def time_since(since):
    s = time.time() - since
    m = math.floor(s/60)
    s -= m*60
    return '%dm %ds' % (m,s)

In [85]:
def train(inp, target):
    hidden = decoder.init_hidden()
    decoder.zero_grad()
    loss=0
    
    for c in range(chunk_len):
        output, hidden = decoder(inp[c], hidden)
        loss += criterion(output, target[c])
        
    loss.backward()
    decoder_optimizer.step()
    
    return loss.data[0] / chunk_len

In [93]:
n_epochs = 2000
print_every = 100
plot_every=10
hidden_size = 100
n_layers = 1
lr = 0.005

decoder = RNN(n_characters, hidden_size, n_characters, n_layers)
decoder_optimizer = torch.optim.Adam(decoder.parameters(), lr=lr)
criterion = nn.CrossEntropyLoss()

start = time.time()
all_losses=[]
loss_avg = 0

for epoch in range(1, n_epochs+1):
    try:
        loss = train(*random_training_set())
        loss_avg += loss

        if epoch % print_every == 0:
            print('[%s (%d %d%%) %.4f]' % (time_since(start), epoch, epoch / n_epochs * 100, loss))
            print(evaluate('R', 100), '\n')

        if epoch % plot_every == 0:
            all_losses.append(loss_avg / plot_every)
            loss_avg = 0
    except:
        continue

[0m 14s (100 5%) 2.2591]
Rutzoe Budy
Benery Atine Wilie
Bika
Bugy
Niusta
Arallie
Cohe Bucy
Farikin
Brkiee
Cascita Ikge Cotoo
L

[0m 29s (200 10%) 2.2650]
Razzs
Pebby
Jaxy
Scarler
Topy
Silly
parlie
Manlie
Pnisty
Jaka
Grarlie
Roxi
Allie
Anddy Bele
Maxie
Dan

[0m 41s (300 15%) 2.2799]
Roe
Kachan
Ludy
Bosie
Mo Duddy
Sadie
Dacy
Chardie
Leolu
Chee
Madie
Caie
Greffanaele
Sumety
Busha
Gunz

[0m 57s (400 20%) 2.1085]
Rog
Steo
Nalie
Rosie
Phippa
Bella
Glow
Maley
Noy
Edge
Mori
Broso
Jena
Sast
Roxie
Lunie
RuEn
Lury
Penn

[1m 12s (500 25%) 1.9606]
RTick
Beana
Bangie
Jack
Shady
Samcka
Samy
Frie
Buntet
Ningie
Millie
Jakis
Stloe
Ostley
Hermo
Gora
Mil

[1m 26s (600 30%) 2.1313]
Remer
Fran
Buddy
Manko
Kobina
Luna
Luna
Maggie
Bear
Marly
Skiter
Louie
Stella
Edillen
Ceria
Benra
Gee

[1m 44s (700 35%) 2.0804]
R-!=die
Max
Toby
Roa
Kila
Stel
Luila
Willson
Pillie
Nella
Oliver
Henry
Gizmo Jasper
Ludelo Wala
Rosi


[1m 58s (800 40%) 1.8430]
Rere
Mazulle Mailey
Shattie
Zo
Sild
Penna
Billy
Clean
Gaxter
Billey
Jogie
Sophar
Bano
Lulu
Gracy
Arry

[2m 13s (900 45%) 2.3792]
Ross
Rosie
Anger
Basen
Reggie Noce
Magimo
Abby
Otherr
Chacous
Max
Shimer
Pockey
Raggie
Ferkie
Lucia
M

[2m 28s (1000 50%) 1.8726]
Romers
Bellu
Riargne
Pocket
Poco
Otzy
Stella
Ricke
Spenney
Pepper
Wintel
Cumpie
Kever
Kari
Spers
Ater

[2m 42s (1100 55%) 1.6792]
Riley
Oliver
Tala
Unie
Luina
Lily
Salia
Iva Leuar
Cassie
Bider
Adie
Bayle
Bear
Darley
Lokie
Emma
Dane

[2m 55s (1200 60%) 1.8144]
Ros Milus
Kindo
Watso
Daxter
Pamna
Lilly
Kili
Finnel
Dojo
Poppy
Laisis Back
Hazella
Rilo
Macher
Baya


[3m 9s (1300 65%) 1.5690]
Rolly
Odie
Maddie
Sam
Rosie
Sius
Bahrsy
Otire
Huper
Harley
Sash
Harney
Belly
Kimpha
Chold
Barby
Samac

[3m 22s (1400 70%) 1.7276]
Rosie
Rocky
Koda
Jese
Whilson
Zish
Misky
Sweer
Lingo
Stanker Jak
Calma
Kamer
Kenchesson
Watsey
Max
Sk

[3m 35s (1500 75%) 1.9990]
Rhoe
Haphs
Alse
Sopper
Samsy
Supper
Flinniger
Chillie
Murper
Rem
Costi
Sophel
Nillie
Bunn
Chewray
Chi

[3m 48s (1600 80%) 2.0263]
Rasmay
Backley
Tento
Rusmey
Cooper
Olivele
Ottis
Sophie
Ricky
Priffrey
Penny
ShengesSie
Gindy
Banjo
B

[4m 4s (1700 85%) 1.7066]
Romer Tugu
Penny
Shill
Murley
Maddie
Sunny
Bandy
Milley
Frigne
Lucy
Laddy
Maggie
Lana
Zankeya
Ellie
S

[4m 22s (1800 90%) 1.7049]
Ranker
Benny Angats
Xyla
Koka
Coji
CabetLun
Harry
Zeke
Shady
Mac
Kauri Lune
Bruie
May
Mia
Zoey
Bofie


[4m 36s (1900 95%) 2.0865]
Roj
Ginger
Cooper
Riny
Churloe
Bodi
Max
Finn
Buster
Daidy
Jackson
Bella
Maxwey
Blicie Baia
Jake
Ruby


[4m 53s (2000 100%) 1.7399]
Rolley
Chamroy
Gingse
Tiannaus
Abby
Izzy
Loui
Kasha
Milo
Butchinke
Bear
Bella
Emmi
Bu Jonessy
Starkst

In [109]:
print(evaluate('f', 200, temperature=0.6))

fle Bell
Rosco
Bella
Margie
Stilla
Sillie
Ziggy
Buster
Poco
Otis
Gobby
Bear
Buther
Jacky
Molly
Mia
Chickon
Roxie
Sammy
Rosi
Lucy
Sophie
Bella
Sasha
Berttinn
King
Sadie
Elillie
Meana
Finn
Kollie
Shadie